# @package _group_
_target_: ntd.datasets.FIFDataLoader
name: fif_example
# Path to the directory containing .fif files or a single .fif file
# Example: '/path/to/your/eeg/data/' or '/path/to/your/eeg/data/subject1.fif'
file_path: ???

# n_channels, sfreq, and n_times (signal length in samples) are inferred from the first valid .fif file.
# All subsequent .fif files must match these inferred parameters, otherwise they will be skipped.

# Maximum number of epochs to load per subject/file.
# If a file has fewer epochs than this number, all its epochs will be loaded.
# If n_epochs is set to null (YAML for None) or 0, all available epochs from each file will be loaded.
# Example: n_epochs: 20 # Loads max 20 epochs per file.
# Example: n_epochs: null # Loads all epochs from all files.
n_epochs: 20 

# Set to True to enable conditioning on subject ID.
# Subject IDs are derived from filenames if multiple files are loaded from a directory.
condition_on_subject_id: False
# Set to True to enable conditioning on class label.
# Class labels are extracted from filenames using the convention: CLASSLABEL_SUBJECTID_*.fif
# e.g., PATIENT_S001_data.fif, CONTROL_S002_data.fif
condition_on_class_label: False

# Example for conditional generation on class_label:
# condition_on_class_label: True
# num_classes: 3 # Specify the total number of unique classes (if known, otherwise it's also inferred by the loader)

# Data shape will be (total_loaded_epochs, n_channels, n_times)
# where n_channels and n_times are inferred from the first valid file.
